name: peer_tube_api_sdk
version: 1.0.9
description: A Dart/Flutter SDK for interacting with PeerTube instances. Easily connect to PeerTube nodes, fetch video data, manage accounts, and more.
homepage: https://github.com/RustLangLatam
repository: https://github.com/RustLangLatam/peertube_api_sdk_dart
issue_tracker: https://github.com/RustLangLatam/peertube_api_sdk_dart/issues
documentation: https://github.com/RustLangLatam/peertube_api_sdk_dart#readme
topics:
  - peertube
  - peertube-api
  - peertube-sdk
  - peer-tube
  - peer-tube-api

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  dio: ^5.8.0+1
  one_of: ^1.5.0
  one_of_serializer: ^1.5.0
  built_value: ^8.9.3
  built_collection: ^5.1.1
  dio_http_formatter: ^3.3.0

dev_dependencies:
  built_value_generator: ^8.9.3
  build_runner: ^2.4.15
  test: ^1.25.15
  lints: ^5.1.1


