//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'confirm_two_factor_request_request.g.dart';

/// ConfirmTwoFactorRequestRequest
///
/// Properties:
/// * [requestToken] - Token to identify the two factor request
/// * [otpToken] - OTP token generated by the app
@BuiltValue()
abstract class ConfirmTwoFactorRequestRequest
    implements
        Built<ConfirmTwoFactorRequestRequest,
            ConfirmTwoFactorRequestRequestBuilder> {
  /// Token to identify the two factor request
  @BuiltValueField(wireName: r'requestToken')
  String get requestToken;

  /// OTP token generated by the app
  @BuiltValueField(wireName: r'otpToken')
  String get otpToken;

  ConfirmTwoFactorRequestRequest._();

  factory ConfirmTwoFactorRequestRequest(
          [void updates(ConfirmTwoFactorRequestRequestBuilder b)]) =
      _$ConfirmTwoFactorRequestRequest;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(ConfirmTwoFactorRequestRequestBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<ConfirmTwoFactorRequestRequest> get serializer =>
      _$ConfirmTwoFactorRequestRequestSerializer();
}

class _$ConfirmTwoFactorRequestRequestSerializer
    implements PrimitiveSerializer<ConfirmTwoFactorRequestRequest> {
  @override
  final Iterable<Type> types = const [
    ConfirmTwoFactorRequestRequest,
    _$ConfirmTwoFactorRequestRequest
  ];

  @override
  final String wireName = r'ConfirmTwoFactorRequestRequest';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    ConfirmTwoFactorRequestRequest object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'requestToken';
    yield serializers.serialize(
      object.requestToken,
      specifiedType: const FullType(String),
    );
    yield r'otpToken';
    yield serializers.serialize(
      object.otpToken,
      specifiedType: const FullType(String),
    );
  }

  @override
  Object serialize(
    Serializers serializers,
    ConfirmTwoFactorRequestRequest object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object,
            specifiedType: specifiedType)
        .toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required ConfirmTwoFactorRequestRequestBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'requestToken':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.requestToken = valueDes;
          break;
        case r'otpToken':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.otpToken = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  ConfirmTwoFactorRequestRequest deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = ConfirmTwoFactorRequestRequestBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}
